# MONAI label

MONAI Label is an intelligent open source image labeling and learning tool that enables users to create annotated datasets and build AI annotation models for clinical evaluation. MONAI Label enables application developers to build labeling apps in a serverless way, where custom labeling apps are exposed as a service through the MONAI Label Server.

## configuration

In [1]:
#check work directory
!pwd

/lustre/workspaces/w54a7mgn/workspace-monailabel-labs


### check available MONAI Label Apps.

In [2]:
# check available apps
!monailabel apps

Using PYTHONPATH=/opt:
Available Apps are:
----------------------------------------------------
  endoscopy                     : /opt/conda/monailabel/sample-apps/endoscopy
  monaibundle                   : /opt/conda/monailabel/sample-apps/monaibundle
  pathology                     : /opt/conda/monailabel/sample-apps/pathology
  radiology                     : /opt/conda/monailabel/sample-apps/radiology



### download radiology and pathology example script

In [5]:
!monailabel apps --download --name radiology --output apps
!monailabel apps --download --name pathology --output apps

Using PYTHONPATH=/opt:
Directory already exists: /home/hryu-nvidia-com/workspace-monailabel-labs/apps/radiology
Using PYTHONPATH=/opt:
pathology is copied at: /home/hryu-nvidia-com/workspace-monailabel-labs/apps/pathology


### Download available Dataset

In [3]:
# check available  sample Datasets
!monailabel datasets # List sample datasets


Using PYTHONPATH=/opt:
Available Datasets are:
----------------------------------------------------
  Task01_BrainTumour            : https://msd-for-monai.s3-us-west-2.amazonaws.com/Task01_BrainTumour.tar
  Task02_Heart                  : https://msd-for-monai.s3-us-west-2.amazonaws.com/Task02_Heart.tar
  Task03_Liver                  : https://msd-for-monai.s3-us-west-2.amazonaws.com/Task03_Liver.tar
  Task04_Hippocampus            : https://msd-for-monai.s3-us-west-2.amazonaws.com/Task04_Hippocampus.tar
  Task05_Prostate               : https://msd-for-monai.s3-us-west-2.amazonaws.com/Task05_Prostate.tar
  Task06_Lung                   : https://msd-for-monai.s3-us-west-2.amazonaws.com/Task06_Lung.tar
  Task07_Pancreas               : https://msd-for-monai.s3-us-west-2.amazonaws.com/Task07_Pancreas.tar
  Task08_HepaticVessel          : https://msd-for-monai.s3-us-west-2.amazonaws.com/Task08_HepaticVessel.tar
  Task09_Spleen                 : https://msd-for-monai.s3-us-west-2.amazon

#### download sample dataset for segmentation 

In [4]:
!monailabel datasets --download --name Task09_Spleen --output datasets
!monailabel datasets --download --name Task06_Lung  --output datasets

Using PYTHONPATH=/opt:
Directory already exists: datasets/Task09_Spleen
Using PYTHONPATH=/opt:
Directory already exists: datasets/Task06_Lung


In [5]:
!monailabel datasets --download --name Task09_Spleen --output datasets
!monailabel datasets --download --name Task06_Lung  --output datasets

Using PYTHONPATH=/opt:
Directory already exists: datasets/Task09_Spleen
Using PYTHONPATH=/opt:
Directory already exists: datasets/Task06_Lung


# launch monai app server

## check allocated port for 9999 port

In [6]:
!cat ~/port_forwarding_command

ssh -L localhost:8888:dgx06:9140 -L localhost:9999:dgx06:10140 ssh.axisapps.io -l 8f7b4f2d689149479812c7050e28a062



#### for example, 
if the port_forwarding_command is below : 
```
ssh -L localhost:8888:dgx05:8730 -L localhost:9999:dgx05:9730 ssh.axisapps.io -l 9bffbbd44d83471292ec7189545006fd
```

check `-L localhost:9999:dgx05:9730` 


- PORT number :  `9730`
- app  : `~/workspace-monailabel-labs/apps/radiology`
- studies :  `~/workspace-monailabel-labs/dataset/Task09_Spleen/imagesTr`
- configure model : segmentation_spleen 

```
monailabel start_server --app  ~/workspace-monailabel-labs/apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models segmentation_spleen --host 0.0.0.0 --port 9730 --verbose DEBUG
```

### launch monai label server ( lung segment)

- step1. copy command ( Control + C)  
- step2. open New terminal 
- step3. (Control + V) in terminal 
- step4. reload and reaccess server in 3D Slicer 

```monailabel start_server --app  ~/workspace-monailabel-labs/apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models segmentation_spleen --host 0.0.0.0 --port 9730 --verbose DEBUG```

In [7]:
import os
os.getcwd()

'/lustre/workspaces/w54a7mgn/workspace-monailabel-labs'

In [8]:
!pwd

/lustre/workspaces/w54a7mgn/workspace-monailabel-labs


### launch monai label server ( deepedit)

- step1. copy command ( Control + C)
- step2. open New terminal
- step3. (Control + V) in terminal
- step4. reload and reaccess server in 3D Slicer

```monailabel start_server --app  ~/workspace-monailabel-labs/apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models deepedit --host 0.0.0.0 --port 9730 --verbose DEBUG```

In [ ]:
monailabel start_server --app  ~/workspace-monailabel-labs/apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models deepedit --host 0.0.0.0 --port 9730 --verbose DEBUG

In [ ]:
monailabel start_server --app  /lustre/workspaces/w54a7mgn/workspace-monailabel-labs/apps/radiology  --studies  /lustre/workspaces/w54a7mgn/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models segmentation_spleen --host 0.0.0.0 --port 10140 --verbose DEBUG

### launch monai label server ( deepgrow_3d)

- step1. copy command ( Control + C)
- step2. open New terminal
- step3. (Control + V) in terminal
- step4. reload and reaccess server in 3D Slicer

```monailabel start_server --app  ~/workspace-monailabel-labs/apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models deepgrow_3d --host 0.0.0.0 --port 9730 --verbose DEBUG```

In [ ]:
# monailabel start_server --app  ~/workspace-monailabel-labs/apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models deepgrow_3d --host 0.0.0.0 --port 9730 --verbose DEBUG



In [9]:
!pip install monailabel

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com

[notice] A new release of pip available: 22.1.2 -> 22.3
[notice] To update, run: pip install --upgrade pip


In [ ]:
monailabel start_server --app  /lustre/workspaces/w54a7mgn/workspace-monailabel-labs/apps/radiology  --studies  /lustre/workspaces/w54a7mgn/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models deepgrow_3d --host 0.0.0.0 --port 10140 --verbose DEBUG

In [ ]:
Task06_Lung

In [ ]:
monailabel start_server --app  /lustre/workspaces/w54a7mgn/workspace-monailabel-labs/apps/radiology  --studies  /lustre/workspaces/w54a7mgn/workspace-monailabel-labs/datasets/Task06_Lung/imagesTr --conf models deepgrow_3d --host 0.0.0.0 --port 10140 --verbose DEBUG

### launch monai label server ( custom model segmentation_lung)

dataset lung 
- step0. copy `apps/libs/configs/segmentation.py` to new `segmentation_lung.py` 
- step1. open and edit label `right lung:1` , `left lung:2` , `airways:3` 
- step2. edit configure  `"use_pretrained_model", "false"` and save
- step3. copy command ( Control + C)
- step4. open New terminal
- step5. (Control + V) in terminal
- step6. reload and reaccess server in 3D Slicer

```monailabel start_server --app  ~/workspace-monailabel-labs/apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task06_Lung/imagesTr --conf models segmentation_lung --host 0.0.0.0 --port 9730 --verbose DEBUG```

In [ ]:
monailabel start_server --app  ~/workspace-monailabel-labs/apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models deepgrow_3d --host 0.0.0.0 --port 9730 --verbose DEBUG



In [ ]:
monailabel start_server --app  ~/workspace-monailabel-labs/apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models deepedit --host 0.0.0.0 --port 9730 --verbose DEBUG



In [ ]:
monailabel start_server --app  ~/workspace-monailabel-labs/apps/radiology  --studies  ~/workspace-monailabel-labs/datasets/Task09_Spleen/imagesTr --conf models segmentaion --host 0.0.0.0 --port 9730 --verbose DEBUG

